### ISSUE TITLE
Bug: p2tr address calculated differently than romeo

### ISSUE THREAD

**Issue by friedger** [stacks-network/sbtc-bridge-api#85]
Romeo engine uses `p2tr` function of the bdk crate to get the taproot address from a public key.

The lib uses btc package and `encode` function. With the `p2tr` function, the same taproot is created as Romeo engine.

See https://github.com/paulmillr/scure-btc-signer/issues/60

**Comment by radicleart** [comment]
Fixed by https://github.com/stacks-network/sbtc-bridge-api/pull/86
